listener 1883 127.0.0.1
protocol mqtt
allow_anonymous false
password_file /data/secrets/mosquitto.passwd
acl_file /data/secrets/mosquitto.acl
persistence true
persistence_location /data/mosquitto/
autosave_interval 60
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
max_queued_messages 1000
